// This file is generated by php artisan nvl:data:types:generate.
// Do not edit this file manually.

/// <reference path="./generated/activity.d.ts" />
/// <reference path="./generated/auth.d.ts" />
/// <reference path="./generated/comments.d.ts" />
/// <reference path="./generated/content.d.ts" />
/// <reference path="./generated/csv.d.ts" />
/// <reference path="./generated/data.d.ts" />
/// <reference path="./generated/filterable.d.ts" />
/// <reference path="./generated/forms.d.ts" />
/// <reference path="./generated/illuminate.d.ts" />
/// <reference path="./generated/mail-notifications.d.ts" />
/// <reference path="./generated/media.d.ts" />
/// <reference path="./generated/metafields.d.ts" />
/// <reference path="./generated/pages.d.ts" />
/// <reference path="./generated/primitives.d.ts" />
/// <reference path="./generated/seo.d.ts" />
/// <reference path="./generated/settings.d.ts" />
/// <reference path="./generated/spatie.d.ts" />
/// <reference path="./generated/tasks.d.ts" />
/// <reference path="./generated/taxonomy.d.ts" />
/// <reference path="./generated/templates.d.ts" />
/// <reference path="./generated/tenancy.d.ts" />
/// <reference path="./generated/translatable.d.ts" />
/// <reference path="./generated/translations.d.ts" />
